
import Head from "next/head";
import { getPost, getSlugs } from '@/lib/post';

export async function getStaticPaths() {
  const slugs = await getSlugs();
  return {
    paths: slugs.map((slug)=>({
      params: { slug},
    })),
    fallback: false, // can also be true or 'blocking'
  };
}
 
export async function getStaticProps({ params: { slug } }) {
  console.log('[PostPage] getStaticProps()', slug);
  const post = await getPost(slug);
  return {
    props: { post },
  };
}


export default function PostPage({post}) {
  console.log('[PostPage] render:', post);
    return (
      <>
       <Head>
        <title>{post.title} - My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
        <h1 className="title-header">{post.title}</h1>
          <div className="container">
          </div>
          <div className="container">
            <p>{post.date}</p>
          <article dangerouslySetInnerHTML={{ __html: post.body }} />
          </div>
        </main>
      </>
    )
  }
  