import Navbar from '@/components/navbar/Navbar'
import Head from 'next/head'
import '@/styles/index.css'


export default function App({ Component, pageProps }) {
  return <>
   <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header>
    <Navbar />
    </header>
    <Component {...pageProps} />
  </>
}
