import Head from "next/head";

export default function ContactPAge() {
    return (
      <>
       <Head>
        <title>Contact - My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
        <p className="title-header">My Contact Page</p>
          <div className="container">
          
          </div>
        </main>
      </>
    )
  }
  